<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2018 rel. 2 sp1 (x64) (http://www.altova.com) by MESMERiZE (MSM) -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:nsf="http://192.168.192.27:8485/services/PetService/v1/faults/" xmlns:ns1="http://192.168.192.27:8485/services/PetService/v1/types/" xmlns:tns="http://192.168.192.27:8485/services/PetService/v1" xmlns:ns="http://192.168.192.27:8485/services/PetService/v1/userContext/" name="PetService" targetNamespace="http://192.168.192.27:8485/services/PetService/v1">
	<wsdl:documentation>Версия 2.0.0</wsdl:documentation>
	<wsdl:types>
		<xs:schema>
			<xs:import namespace="http://192.168.192.27:8485/services/PetService/v1/faults/" schemaLocation="emias.system.v1.faults.xsd"/>
			<xs:import namespace="http://192.168.192.27:8485/services/PetService/v1/types/" schemaLocation="services.PetService.v1.types.xsd"/>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="getPushInput">
		<wsdl:part name="body" element="ns1:getPushRequest"/>
	</wsdl:message>
	<wsdl:message name="getPushOutput">
		<wsdl:part name="body" element="ns1:getPushResponse"/>
	</wsdl:message>
	<wsdl:message name="fault">
		<wsdl:documentation>Ошибка</wsdl:documentation>
		<wsdl:part name="body" element="nsf:fault"/>
	</wsdl:message>
	<wsdl:portType name="PetServicePortType">
		<wsdl:operation name="getPush">
			<wsdl:documentation>Получение пуш-уведомления о событии с медицинским документом</wsdl:documentation>
			<wsdl:input message="tns:getPushInput"/>
			<wsdl:output message="tns:getPushOutput"/>
			<wsdl:fault name="fault" message="tns:fault"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="PetServiceBinding" type="tns:PetServicePortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="getPush">
			<soap:operation soapAction="getPush"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="fault">
				<soap:fault name="fault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="PetService">
		<wsdl:documentation>Сервис обработки пушей</wsdl:documentation>
		<wsdl:port name="PetServicePortType" binding="tns:PetServiceBinding">
			<soap:address location="REPLACE_WITH_ACTUAL_URL"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
